export 'package:flutter/material.dart';
export 'package:flutter_screenutil/flutter_screenutil.dart';
export 'package:gather_app/widgets/text_widget.dart';
export '../../utils/colors.dart';
export 'package:gap/gap.dart';
export 'package:gather_app/screens/favorites/screens/favourite_screen.dart';
export 'package:gather_app/screens/profile/screens/profile_screen.dart';
export 'package:gather_app/screens/searchscreen/screens/search_screen.dart';
export 'package:gather_app/screens/home/screens/home_screen.dart';